### ISSUE TITLE
Jeffy

### ISSUE THREAD

**Issue by igniuss** [JGray0705/ImgurSharp#1]
https://github.com/JGray0705/ImgurSharp/blob/668a2e924ec823b73e5a3dc67decfe62bd6ca4e2/ImgurConsole/Program.cs#L9

RIP api key

Look at a way of hiding api keys, there's a fairly easy way to do it as well using partial classes (see [here](https://stackoverflow.com/a/21814021))

**Comment by JGray0705** [comment]
Perfect, fixed.
